# Generated by Django 6.0.4 on 2026-04-21 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jogador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('formato', models.CharField(choices=[('pontos_corridos', 'Pontos Corridos'), ('grupos_mata_mata', 'Grupos + Mata-Mata')], default='pontos_corridos', max_length=20)),
                ('jogos_ida_volta', models.BooleanField(default=False)),
                ('criterios_desempate', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('encerrado', 'Encerrado')], default='rascunho', max_length=10)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('escudo_url', models.URLField(blank=True)),
                ('cor', models.CharField(blank=True, max_length=10)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='core.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='JogadorTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times_campeonato', to='core.jogador')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores_time', to='core.timecampeonato')),
            ],
            options={
                'unique_together': {('time', 'jogador')},
            },
        ),
    ]
