# Generated by Django 6.0.4 on 2026-05-03 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campeonato_timecampeonato_jogadortime'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='modalidade',
            field=models.CharField(choices=[('futebol', 'Futebol'), ('futsal', 'Futsal')], default='futebol', max_length=10),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='pontos_derrota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='pontos_empate',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='pontos_vitoria',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='tipo',
            field=models.CharField(choices=[('pequeno', 'Pequeno (5 times)'), ('medio', 'Médio (10 times)'), ('grande', 'Grande (20 times)')], default='pequeno', max_length=10),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_casa', models.PositiveIntegerField(blank=True, null=True)),
                ('gols_fora', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('encerrada', 'Encerrada')], default='agendada', max_length=10)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='core.campeonato')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_casa', to='core.timecampeonato')),
                ('time_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_fora', to='core.timecampeonato')),
            ],
        ),
    ]
