# Generated by Django 6.0.4 on 2026-05-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campeonato_modalidade_campeonato_pontos_derrota_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organizador',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='rodada',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
