# Generated by Django 6.0.4 on 2026-05-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_organizador_managers_partida_rodada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='tipo',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='pequeno', max_length=10),
        ),
        migrations.AlterField(
            model_name='partida',
            name='rodada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
