# Generated by Django 6.0.4 on 2026-05-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_campeonato_tipo_alter_partida_rodada'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='local',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
