# Generated by Django 6.0.4 on 2026-05-14 20:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_time_timecampeonato_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='modalidade',
            field=models.CharField(choices=[('futebol_masculino', 'Futebol Masculino'), ('futsal_masculino', 'Futsal Masculino'), ('futebol_feminino', 'Futebol Feminino'), ('futsal_feminino', 'Futsal Feminino')], default='futebol_masculino', max_length=20),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nivel_estrelas',
            field=models.FloatField(choices=[(0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5')], default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.CreateModel(
            name='JogoCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(blank=True, max_length=100)),
                ('gols_casa', models.PositiveIntegerField(blank=True, null=True)),
                ('gols_fora', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada')], default='agendada', max_length=10)),
                ('rodada', models.PositiveIntegerField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='core.campeonato')),
                ('time_casa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='core.timecampeonato')),
                ('time_visitante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='core.timecampeonato')),
            ],
        ),
        migrations.DeleteModel(
            name='Partida',
        ),
    ]
