# Generated by Django 6.0.3 on 2026-05-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_campeonato_modalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='classificados_por_grupo',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='num_grupos',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='jogocampeonato',
            name='fase',
            field=models.CharField(choices=[('grupos', 'Fase de Grupos'), ('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semi', 'Semifinal'), ('final', 'Final')], default='grupos', max_length=10),
        ),
        migrations.AddField(
            model_name='timecampeonato',
            name='grupo',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
