# Generated by Django 6.0.3 on 2026-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_campeonato_classificados_por_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], default='masculino', max_length=10),
        ),
    ]
