# Generated by Django 6.0.3 on 2026-05-28 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_time_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='modalidade',
            field=models.CharField(choices=[('futebol_masculino', 'Futebol Masculino'), ('futebol_feminino', 'Futebol Feminino')], default='futebol_masculino', max_length=20),
        ),
        migrations.CreateModel(
            name='JogadorDoTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('numero', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elenco', to='core.time')),
            ],
        ),
    ]
