# Generated by Django 6.0.3 on 2026-06-04 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cartao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='core.jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='core.jogocampeonato')),
            ],
            options={
                'verbose_name': 'Gol',
                'verbose_name_plural': 'Gols',
            },
        ),
    ]
