# Generated by Django 6.0.3 on 2026-06-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_gol'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='regulamento',
            field=models.TextField(blank=True),
        ),
    ]
