# Generated by Django 6.0.3 on 2026-06-09 03:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_regulamento_campeonato'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='escudo',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='JogadorTimeCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nivel_estrelas', models.FloatField(choices=[(0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)])),
                ('time_campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elenco_campeonato', to='core.timecampeonato')),
            ],
            options={
                'unique_together': {('time_campeonato', 'nome')},
            },
        ),
    ]
