# Generated by Django 6.0.3 on 2026-06-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_escudo_time_jogador_time_campeonato'),
    ]

    operations = [
        migrations.AddField(
            model_name='gol',
            name='assistencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistencias', to='core.jogadortimecampeonato'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='core.jogadortimecampeonato'),
        ),
        migrations.AlterField(
            model_name='gol',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='core.jogadortimecampeonato'),
        ),
    ]
