# Generated by Django 6.0.4 on 2026-06-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_gol_assistencia_alter_cartao_jogador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadordotime',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros_time', to='core.jogador'),
        ),
        migrations.AlterUniqueTogether(
            name='jogadordotime',
            unique_together={('time', 'jogador')},
        ),
    ]
