# Generated by Django 6.0.3 on 2026-06-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_jogadordotime_fk_jogador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='genero',
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='modalidade',
            field=models.CharField(choices=[('futebol', 'Futebol')], default='futebol', max_length=20),
        ),
    ]
