# Generated by Django 6.0.3 on 2026-06-18 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_genero_simplify_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='jogos_suspensao_vermelho',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartao',
            name='conta_acumulo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Suspensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('acumulo_amarelos', 'Acúmulo de Amarelos'), ('duplo_amarelo', 'Duplo Amarelo (Expulsão)'), ('vermelho_direto', 'Cartão Vermelho Direto')], max_length=20)),
                ('jogos_restantes', models.PositiveIntegerField(default=1)),
                ('cumprida', models.BooleanField(default=False)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes', to='core.campeonato')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes', to='core.jogadortimecampeonato')),
                ('jogo_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes_geradas', to='core.jogocampeonato')),
            ],
            options={
                'verbose_name': 'Suspensão',
                'verbose_name_plural': 'Suspensões',
            },
        ),
    ]
